#pragma once

#define APP_TITLE "ESP32CAM-RTSP"
#define APP_VERSION "1.0"

#define WIFI_SSID "ESP32CAM-RTSP"
#define WIFI_PASSWORD nullptr
#define CONFIG_VERSION "1.1"

#define RTSP_PORT 554
#define DEFAULT_FRAMERATE "20"
#define DEFAULT_FRAMESIZE "SVGA (800x600)"